name: GitHub Actions Exploring Demo1
run-name: '${{ github.actor }} is exploring GitHub Actions'
'on':
#   - push
  - workflow_dispatch
jobs:
  Explore-GitHub-Actions-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Exp-actions-job1-name1
        run: 'echo "Automatically triggered by a ${{ github.event_name }} event."'
        
      - run: 'echo "Running on a ${{ runner.os }} server hosted by GitHub."'

      - run: 'echo "Repository is ${{ github.repository }}."'
      
      - name: Check out repository and Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'
           
#      - run: python my_script.py

      - name: Python Pylint Github Actions for Code Analysis
        run: |
            python -m pip install --upgrade pip
            pip install pylint
            
      - name: Analysing the code with pylint
        run: |
           #find . -name'inventory_demoapp.p' -exec pylint {} \;
           #find . -name '*.py' -exec pylint {} \;
           pylint inventory_demoapp.py
                   
      - run: 'echo "This job status is ${{ job.status }}."'
