# Github Workflow for testing secrets
name: Github Secrets test
on:
  workflow_dispatch:

env:
  WORK_FLOW_LEVEL: Vijai Kannan

jobs:
  Github-secrets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Testing
        env: 
            repo_secret_passwd: ${{secrets.SECRET_PASSWD}}
        run: |
            if [ "$repo_secret_passwd" != "breeze" ]
            then
              echo "Oops incorrect password for SECRET_PASSWD under ${GITHUB_REPOSITORY}. Please try again "
            fi
            echo " $repo_secret_passwd ... correct Password " 



